version: "3.8"

services:
  backend:
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run dev"

  frontend:
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3000
    command: sh -c "npm install && npm run dev"
